### ISSUE TITLE
400-clean cannot remove link as subdirectory

### ISSUE THREAD

**Issue by remi-filament** [Tecnativa/doodba#189]
During build, while trying to clean out unused modules, I face the following error : 
```
INFO:docker-odoo-base:Removing subdirectory /opt/odoo/custom/src/bank-statement-import/account_bank_statement_import_camt_oca
Traceback (most recent call last):
  File "400-clean", line 41, in <module>
    shutil.rmtree(subfull)
  File "/usr/lib/python2.7/shutil.py", line 232, in rmtree
    onerror(os.path.islink, path, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 230, in rmtree
    raise OSError("Cannot call rmtree on a symbolic link")
OSError: Cannot call rmtree on a symbolic link
```
The issue comes from a specific module in bank-statement-import OCA repo : [account_bank_statement_import_oca](https://github.com/OCA/bank-statement-import/blob/10.0/account_bank_statement_import_camt_oca) which is a symlink to the same module without _oca at the end.

Not cleaning the repositories works around the issue (adding CLEAN = false), but we may face the same issue with another module,

Since 400-clean is already not cleaning individual files at root of directories and subdirectories, a possible solution would be to check if directory or subdirectory are not links as well (although it would then leave dead links, therefore not sure this is ideal solution).
If you consider this would do the trick, I can provide a PR with the following code changes:

L22 : `if not (os.path.isdir(full) or os.path.islink(full)):`
L35 : `if not (os.path.isdir(subfull) or os.path.islink(subfull)):`

**Comment by Yajo** [comment]
Please open that PR and let's discuss on it.

Maybe you can try an easier approach of something similar to:

```python
try:
  shutil.rmtree(subfull)
except OSError:
  os.unlink(subfull)
```

[EAFP](https://docs.python.org/3/glossary.html#term-eafp).

**Comment by remi-filament** [comment]
Done, thanks for the tip with try/catch solution, it worked.
