### ISSUE TITLE
shallow.lock': File exists.

### ISSUE THREAD

**Issue by feelappcloud** [Tecnativa/doodba#219]
when I was running this command "docker-compose -f setup-devel.yaml run - rm odoo" my computer restarted and when I try to use the same code again I get the following error:

where is the location of the "shallow.lock"? try to find it in the path of my files but nothing, any suggestions?

"fatal: Unable to create '/opt/odoo/custom/src/odoo/.git/shallow.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/git_aggregator/main.py", line 204, in aggregate_repo
    repo.aggregate()
  File "/usr/local/lib/python3.5/site-packages/git_aggregator/repo.py", line 179, in aggregate
    self.fetch()
  File "/usr/local/lib/python3.5/site-packages/git_aggregator/repo.py", line 202, in fetch
    self.log_call(cmd, cwd=self.cwd)
  File "/usr/local/lib/python3.5/site-packages/git_aggregator/repo.py", line 159, in log_call
    ret = callwith(cmd, **kw)
  File "/usr/local/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('git', 'fetch', '--depth', '100', 'ocb', '11.0')' returned non-zero exit status 128
Traceback (most recent call last):
  File "/usr/local/bin/autoaggregate", line 129, in <module>
    aggregate(REPOS_YAML)
  File "/usr/local/bin/autoaggregate", line 43, in aggregate
    stdout=sys.stdout,
  File "/usr/local/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gitaggregate', '--expand-env', '--config', '/opt/odoo/custom/src/repos.yaml', '--jobs', '4']' returned non-zero exit status 1"

**Comment by Yajo** [comment]
Just run:

```
docker-compose run --rm odoo rm /opt/odoo/custom/src/odoo/.git/shallow.lock
```
