### ISSUE TITLE
Odoo 12.0 tests for web module do not work inside doodba

### ISSUE THREAD

**Issue by ap-wtioit** [Tecnativa/doodba#234]
When running tests for Odoo 12.0 the tests for module "web" always throw an error whereas on http://runbot.odoo.com/runbot they run successful (at least some times).
inside of smallest, https://github.com/Tecnativa/doodba/tree/master/tests/scaffoldings/smallest:
```
ODOO_MINOR=12.0 DB_VERSION=10 docker-compose build --pull
ODOO_MINOR=12.0 DB_VERSION=10 docker-compose run --rm odoo odoo -i base --test-enable --stop-after-init
```
It always fails with:
```
2019-08-09 11:27:35,676 1 INFO prod odoo.addons.web.tests.test_js.WebSuite: console log: "fields > basic_fields > PhoneWidget" passed 18 tests. 
2019-08-09 11:27:35,733 1 INFO prod odoo.addons.web.tests.test_js.WebSuite: console log: "fields > relational_fields > FieldOne2Many" passed 9 tests. 
2019-08-09 11:27:35,745 1 INFO prod odoo.addons.web.tests.test_js.WebSuite: console log: "Base Import Mobile Tests" passed 2 tests. 
2019-08-09 11:27:35,746 1 INFO prod odoo.addons.web.tests.test_js.WebSuite: console log: ok 
2019-08-09 11:27:35,747 1 INFO prod odoo.addons.web.tests.test_js.WebSuite: Deleting cookies and clearing local storage 
2019-08-09 11:27:35,756 1 INFO prod odoo.addons.web.tests.test_js.WebSuite: Navigating to: "about:blank" 
2019-08-09 11:27:35,757 1 INFO prod odoo.addons.web.tests.test_js.WebSuite: Navigation result: {'result': {'frameId': 'D8618ED2987CA84189D76279A7D3DEE5', 'loaderId': '3200D8FA410DF5B2FC541E37980DDBE3'}, 'id': 19} 
2019-08-09 11:27:35,757 1 INFO prod odoo.addons.web.tests.test_js.WebSuite: Waiting for frame "D8618ED2987CA84189D76279A7D3DEE5" to stop loading 
2019-08-09 11:27:35,764 1 INFO prod odoo.addons.web.tests.test_js: test_check_suite (odoo.addons.web.tests.test_js.WebSuite) 
2019-08-09 11:27:37,301 1 INFO prod odoo.addons.web.tests.test_js.WebSuite: Closing chrome headless with pid 40 
2019-08-09 11:27:37,301 1 INFO prod odoo.addons.web.tests.test_js.WebSuite: Terminating chrome headless with pid 40 
2019-08-09 11:27:37,312 1 INFO prod odoo.addons.web.tests.test_js.WebSuite: Removing chrome user profile "/tmp/tmpfi5ornfv_chrome_odoo" 
2019-08-09 11:27:37,322 1 INFO prod odoo.addons.web.tests.test_js: ====================================================================== 
2019-08-09 11:27:37,322 1 ERROR prod odoo.addons.web.tests.test_js: FAIL: test_01_js (odoo.addons.web.tests.test_js.WebSuite) 
2019-08-09 11:27:37,322 1 ERROR prod odoo.addons.web.tests.test_js: Traceback (most recent call last): 
2019-08-09 11:27:37,322 1 ERROR prod odoo.addons.web.tests.test_js: `   File "/opt/odoo/auto/addons/web/tests/test_js.py", line 15, in test_01_js 
2019-08-09 11:27:37,322 1 ERROR prod odoo.addons.web.tests.test_js: `     self.phantom_js('/web/tests?mod=web&failfast', "", "", login='admin', timeout=1800) 
2019-08-09 11:27:37,322 1 ERROR prod odoo.addons.web.tests.test_js: `   File "/opt/odoo/custom/src/odoo/odoo/tests/common.py", line 947, in browser_js 
2019-08-09 11:27:37,322 1 ERROR prod odoo.addons.web.tests.test_js: `     self.assertTrue(self.browser._wait_code_ok(code, timeout), message) 
2019-08-09 11:27:37,322 1 ERROR prod odoo.addons.web.tests.test_js: ` AssertionError: False is not true : Some js test failed 
2019-08-09 11:27:37,322 1 INFO prod odoo.addons.web.tests.test_js: Ran 3 tests in 1818.970s 
2019-08-09 11:27:37,322 1 ERROR prod odoo.addons.web.tests.test_js: FAILED 
2019-08-09 11:27:37,322 1 INFO prod odoo.addons.web.tests.test_js:  (failures=1) 
2019-08-09 11:27:37,322 1 INFO prod odoo.modules.module: odoo.addons.web.tests.test_js tested in 1818.97s, 1795 queries 
```
If you do not drop your database between runs you need to do use -u for the consecutive runs:
```
ODOO_MINOR=12.0 DB_VERSION=10 docker-compose run --rm odoo odoo -u base --test-enable --stop-after-init
```

**Comment by Yajo** [comment]
Can you paste please the full logs? I think you swallowed the important part.

**Comment by ap-wtioit** [comment]
Here are the two full logs:
* [Log from `docker-compose build`: build.log](https://github.com/Tecnativa/doodba/files/3491622/build.log)
* [Log from docker-compose run: test.log](https://github.com/Tecnativa/doodba/files/3491623/test.log)

I will most likely only have time in September to investigate this further. I already tested updating the image locally with a newer chrome but that didn't help.

**Comment by Yajo** [comment]
I recently found the issue myself and the fix was to increase some limits. Just with  `limit_memory_hard=34359740000` all tests passed, but I guess you could try with other limits too.

Before v12, limits only affected workers; but in v12 they seem to affect threads too (which is the mode used to run tests; a.k.a. `--workers 0`), so this problem started to appear.

Please reopen if it still happens.

**Comment by ap-wtioit** [comment]
thks, `limit_memory_hard=...` fixes this for v12
