### ISSUE TITLE
auth_* causes session expired

### ISSUE THREAD

**Issue by jans23** [Tecnativa/doodba#283]
On our doodba test/dev setup some users experienced a session timeout (see below) when accessing Odoo, even in a new incognito browser window without being loged in. It didn't happen to all users but to some. Uninstalling auth_u2f and auth_session_timeout solved the issue. However we would like to use those modules and therefore need a better solution. This might be related to Access-Control-Allow-Origin and similar headers and their values being mismatched between what the browser sees and what Odoo knows about itself. Any idea?

```
odoo.http.SessionExpiredException

odoo.http.SessionExpiredException: Session expired
Traceback (most recent call last)

    File "/opt/odoo/custom/src/odoo/odoo/service/wsgi_server.py", line 140, in application

    return ProxyFix(application_unproxied)(environ, start_response)

    File "/home/odoo/.local/lib/python3.5/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__

    return self.app(environ, start_response)

    File "/opt/odoo/custom/src/odoo/odoo/service/wsgi_server.py", line 117, in application_unproxied

    result = odoo.http.root(environ, start_response)

    File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1320, in __call__

    return self.dispatch(environ, start_response)

    File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1293, in __call__

    return self.app(environ, start_wrapped)

    File "/home/odoo/.local/lib/python3.5/site-packages/werkzeug/wsgi.py", line 766, in __call__

    return self.app(environ, start_response)

    File "/opt/odoo/custom/src/odoo/odoo/http.py", line 1488, in dispatch

    result = ir_http._dispatch()

    File "/opt/odoo/custom/src/odoo/addons/website_sale/models/ir_http.py", line 15, in _dispatch

    return super(IrHttp, cls)._dispatch()

    File "/opt/odoo/custom/src/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch

    return super(Http, cls)._dispatch()

    File "/opt/odoo/custom/src/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch

    return super(IrHttp, cls)._dispatch()

    File "/opt/odoo/custom/src/odoo/addons/http_routing/models/ir_http.py", line 356, in _dispatch

    return cls._handle_exception(e)

    File "/opt/odoo/custom/src/odoo/addons/website/models/ir_http.py", line 195, in _handle_exception

    return super(Http, cls)._handle_exception(exception)

    File "/opt/odoo/custom/src/odoo/addons/utm/models/ir_http.py", line 31, in _handle_exception

    response = super(IrHttp, cls)._handle_exception(exc)

    File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_http.py", line 174, in _handle_exception

    raise exception

    File "/opt/odoo/custom/src/odoo/addons/http_routing/models/ir_http.py", line 352, in _dispatch

    cls._authenticate(func.routing['auth'])

    File "/opt/odoo/custom/src/server-auth/auth_session_timeout/models/ir_http.py", line 14, in _authenticate

    request.env.user._auth_timeout_check()

    File "/opt/odoo/custom/src/server-auth/auth_session_timeout/models/res_users.py", line 89, in _auth_timeout_check

    raise SessionExpiredException("Session expired")

    odoo.http.SessionExpiredException: Session expired
```

**Comment by Yajo** [comment]
> On our doodba test/dev setup some users experienced a session timeout [...] Uninstalling auth_u2f and auth_session_timeout solved the issue.

It seems like your modules are misconfigured or buggy. In any case, doodba is not the place to get support about those modules; you should probably open an issue in the respective projects.
