### ISSUE TITLE
Trying copier on fresh Debian 10 install

### ISSUE THREAD

**Issue by bosd** [Tecnativa/doodba#314]
I've setup a fresh host Debian 10 vps.
Tried multiple fresh installs of Debian 10, but was unable to get an project up and running.
Tried multiple combinations of odoo and postgres versions as well.
Yet, it keeps breaking on file not found error.
What's going wrong here?

<details>
<summary>logs</summary>
copy of odoo log

 ``` 
~/myproject$ sudo docker-compose -f test.yaml up
[sudo] password for user: 

WARNING: The SMTP_REAL_NON_CANONICAL_DEFAULT variable is not set. Defaulting to a blank string.
Starting myproject_db_1   ... done
Starting myproject_smtp_1 ... done
Starting myproject_odoo_1 ... done
Attaching to myproject_smtp_1, myproject_db_1, myproject_odoo_1
db_1    | 
db_1    | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1    | 
db_1    | 2020-06-08 09:48:42.127 GMT [1] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.2.0) 9.2.0, 64-bit
db_1    | 2020-06-08 09:48:42.127 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1    | 2020-06-08 09:48:42.127 GMT [1] LOG:  listening on IPv6 address "::", port 5432
db_1    | 2020-06-08 09:48:42.131 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1    | 2020-06-08 09:48:42.154 GMT [20] LOG:  database system was shut down at 2020-06-08 08:27:08 GMT
db_1    | 2020-06-08 09:48:42.166 GMT [1] LOG:  database system is ready to accept connections
smtp_1  | 2020/06/08 09:48:41 Using in-memory storage
smtp_1  | 2020/06/08 09:48:41 [SMTP] Binding to address: 0.0.0.0:1025
smtp_1  | 2020/06/08 09:48:41 Serving under http://0.0.0.0:8025/
smtp_1  | [HTTP] Binding to address: 0.0.0.0:8025
smtp_1  | Creating API v1 with WebPath: 
smtp_1  | Creating API v2 with WebPath: 
odoo_1  | /usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
odoo_1  |   """)
odoo_1  | doodba INFO: Waiting until postgres is listening at db...
odoo_1  | doodba INFO: Linking all addons from /opt/odoo/custom/src/addons.yaml in /opt/odoo/auto/addons
odoo_1  | doodba INFO: File /opt/odoo/auto/odoo.conf exists, skipping config generation
odoo_1  | doodba INFO: Executing odoo --workers=2 --max-cron-threads=1
odoo_1  | Traceback (most recent call last):
odoo_1  |   File "/opt/odoo/common/entrypoint", line 61, in <module>
odoo_1  |     os.execvp(extra_command[0], extra_command)
odoo_1  |   File "/usr/local/lib/python3.6/os.py", line 559, in execvp
odoo_1  |     _execvpe(file, args)
odoo_1  |   File "/usr/local/lib/python3.6/os.py", line 604, in _execvpe
odoo_1  |     raise last_exc.with_traceback(tb)
odoo_1  |   File "/usr/local/lib/python3.6/os.py", line 594, in _execvpe
odoo_1  |     exec_func(fullname, *argrest)
odoo_1  | FileNotFoundError: [Errno 2] No such file or directory
odoo_1  | /usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
odoo_1  |   """)
odoo_1  | doodba INFO: Waiting until postgres is listening at db...
odoo_1  | doodba INFO: Linking all addons from /opt/odoo/custom/src/addons.yaml in /opt/odoo/auto/addons
odoo_1  | doodba INFO: File /opt/odoo/auto/odoo.conf exists, skipping config generation
odoo_1  | doodba INFO: Executing odoo --workers=2 --max-cron-threads=1
odoo_1  | Traceback (most recent call last):
odoo_1  |   File "/opt/odoo/common/entrypoint", line 61, in <module>
odoo_1  |     os.execvp(extra_command[0], extra_command)
odoo_1  |   File "/usr/local/lib/python3.6/os.py", line 559, in execvp
odoo_1  |     _execvpe(file, args)
odoo_1  |   File "/usr/local/lib/python3.6/os.py", line 604, in _execvpe
odoo_1  |     raise last_exc.with_traceback(tb)
odoo_1  |   File "/usr/local/lib/python3.6/os.py", line 594, in _execvpe
odoo_1  |     exec_func(fullname, *argrest)
odoo_1  | FileNotFoundError: [Errno 2] No such file or directory
myproject_odoo_1 exited with code 1

```
</details>

**Comment by bosd** [comment]
Similar issue on a ubuntu host. so this does not seems to be host related.
More due to the test and prod environment

**Comment by bosd** [comment]
after some more trial and error. It had to do with the entrypoint.
Somehow it got corrupted during install.

My workaround is to delete the folder
` odoo/custom/entrypoint
and then
```
$ mkdir entrypoint.d
$ chmod 777 ./entrypoint.d
```
following with
``$ myproject/   chmod 777 ./entrypoint.d

**Comment by bosd** [comment]
for some reason the invoke commands keep throwing an error:
```Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```
