### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by manuelregidor** [Tecnativa/doodba#321]
Hi @Yajo ,

I'm using dooba on odoo 13 and I'm getting an error when doing docker-compose up. The user is in the docker permission group. I have done the build and download addons steps. I have given permissions to the addons folder where soft-links are created with "chmod -R ug+rwX odoo/auto". I have included the -i command to create the initial db if it does not exist and I have deleted the .empty files. I'm using ubuntu 18.04. Do you know what could be wrong?

Thank you

PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1          | 
db_1          | 2020-08-14 07:55:26.352 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1          | 2020-08-14 07:55:26.352 GMT [1] LOG:  listening on IPv6 address "::", port 5432
db_proxy_1    | INFO:root:Executing: socat tcp-listen:5432,fork,reuseaddr tcp-connect:db:5432
odoo_1        | doodba INFO: Waiting until postgres is listening at db...
odoo_1        | doodba INFO: Linking all addons from /opt/odoo/custom/src/addons.yaml in /opt/odoo/auto/addons
odoo_1        | Traceback (most recent call last):
odoo_1        |   File "/opt/odoo/common/entrypoint.d/40-addons-link", line 17, in <module>
db_1          | 2020-08-14 07:55:26.354 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
odoo_1        |     os.symlink(src, dst)
odoo_1        | PermissionError: [Errno 13] Permission denied: '../../custom/src/account_financial_reporting/account_financial_report' -> '/opt/odoo/auto/addons/account_financial_report'
odoo_1        | Traceback (most recent call last):
odoo_1        |   File "/opt/odoo/common/entrypoint", line 32, in <module>
odoo_1        |     subprocess.check_call(command)
odoo_1        |   File "/usr/local/lib/python3.6/subprocess.py", line 311, in check_call
db_1          | 2020-08-14 07:55:26.366 GMT [20] LOG:  database system was shut down at 2020-08-14 07:52:02 GMT
odoo_1        |     raise CalledProcessError(retcode, cmd)
odoo_1        | subprocess.CalledProcessError: Command '/opt/odoo/common/entrypoint.d/40-addons-link' returned non-zero exit status 1.
db_1          | 2020-08-14 07:55:26.370 GMT [1] LOG:  database system is ready to accept connections
odoo_1 exited with code 1

**Comment by Yajo** [comment]
What's your environment? devel/test/prod

Run these commands and tell me the result please:

```sh
id
docker-compose run --rm odoo id
```

**Comment by manuelregidor** [comment]
I'm on a devel environment.

id:
uid=1001(manu) gid=1001(manu) grupos=1001(manu),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),118(lpadmin),126(sambashare),999(docker)

docker-compose run --rm odoo id:
manu@manu-XPS-13-7390:~/Documentos/proyectos/client$ docker-compose run --rm odoo id
WARNING: The DOMAIN_PROD variable is not set. Defaulting to a blank string.
Creating network "client_default" with the default driver
Creating network "client_public" with the default driver
Creating client_db_1 ... done
doodba INFO: Waiting until postgres is listening at db...
doodba WARNING: Attempt to install unaccent in client@db failed with this message: psql: error: could not connect to server: FATAL: database "client" does not exist
doodba INFO: Linking all addons from /opt/odoo/custom/src/addons.yaml in /opt/odoo/auto/addons
Traceback (most recent call last):
  File "/opt/odoo/common/entrypoint.d/40-addons-link", line 17, in <module>
    os.symlink(src, dst)
PermissionError: [Errno 13] Permission denied: '../../custom/src/l10n_spain/l10n_es_vat_book' -> '/opt/odoo/auto/addons/l10n_es_vat_book'
Traceback (most recent call last):
  File "/opt/odoo/common/entrypoint", line 32, in <module>
    subprocess.check_call(command)
  File "/usr/local/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/odoo/common/entrypoint.d/40-addons-link' returned non-zero exit status 1

**Comment by Yajo** [comment]
Run: `docker-compose run --rm --entrypoint id odoo`

**Comment by estraka** [comment]
Hi, I have the same problem in odoo V12.0

Previously it was running correctly, but I have had many problems with my system, and I have been doing updates ... I do not know if it could be the problem, or it will be some change of DOODBA, because I rebuilt all my containers.

I'm using Mac OS 10.15

Error: 

```
odoo_1                    | Traceback (most recent call last):
odoo_1                    |   File "/opt/odoo/common/entrypoint", line 32, in <module>
odoo_1                    |     subprocess.check_call(command)
odoo_1                    |   File "/usr/local/lib/python3.5/subprocess.py", line 266, in check_call
odoo_1                    |     retcode = call(*popenargs, **kwargs)
odoo_1                    |   File "/usr/local/lib/python3.5/subprocess.py", line 247, in call
odoo_1                    |     with Popen(*popenargs, **kwargs) as p:
odoo_1                    |   File "/usr/local/lib/python3.5/subprocess.py", line 676, in __init__
odoo_1                    |     restore_signals, start_new_session)
odoo_1                    |   File "/usr/local/lib/python3.5/subprocess.py", line 1289, in _execute_child
odoo_1                    |     raise child_exception_type(errno_num, err_msg)
odoo_1                    | PermissionError: [Errno 13] Permission denied
```

When I execute: id

uid=501(estraka) gid=20(staff) groups=20(staff),12(everyone),61(localaccounts),79(_appserverusr),80(admin),81(_appserveradm),98(_lpadmin),33(_appstore),100(_lpoperator),204(_developer),250(_analyticsusers),395(com.apple.access_ftp),398(com.apple.access_screensharing),399(com.apple.access_ssh),400(com.apple.access_remote_ae),701(com.apple.sharepoint.group.1)

**Comment by estraka** [comment]
Executing :
> Run: docker-compose run --rm --entrypoint id odoo

I have de same result.

**Comment by estraka** [comment]
All day testing, and I can say that it is something related to my system (I have the same problem on 2 Macs, one just formatted) ... because I just did an installation on Ubuntu 20.04 and it worked.

@manuelregidor  How did you solve it? I am very lost and it is already several days like this and I do not know where to look for my problem.

**Comment by estraka** [comment]
Hi!
I have news about my problem. I just got my Odoo installation working. I had to delete `odoo/custom/entrypoint.d/.empty ` and it started working.

@Yajo What is the purpose of that file?

**Comment by HaraldPanten** [comment]
I think that some empties files ara creating inconsistances for mac

**Comment by manuelregidor** [comment]
Hi @estraka, Deleting .empty files and changing permissions usually work for me.
