### ISSUE TITLE
--dev=reload doesn't work

### ISSUE THREAD

**Issue by yelizariev** [Tecnativa/doodba#329]
I'm contantly getting this error after saving files (tested in spacemacs, nano, xed)
```

odoo_1                    | 2020-10-15 11:39:18,376 1 INFO ? odoo.service.server: Watching addons folder /opt/odoo/auto/addons 
odoo_1                    | Traceback (most recent call last):
odoo_1                    |   File "/usr/local/bin/odoo", line 8, in <module>
odoo_1                    |     odoo.cli.main()
odoo_1                    |   File "/opt/odoo/custom/src/odoo/odoo/cli/command.py", line 61, in main
odoo_1                    |     o.run(args)
odoo_1                    |   File "/opt/odoo/custom/src/odoo/odoo/cli/server.py", line 178, in run
odoo_1                    |     main(args)
odoo_1                    |   File "/opt/odoo/custom/src/odoo/odoo/cli/server.py", line 172, in main
odoo_1                    |     rc = odoo.service.server.start(preload=preload, stop=stop)
odoo_1                    |   File "/opt/odoo/custom/src/odoo/odoo/service/server.py", line 1284, in start
odoo_1                    |     watcher = FSWatcherInotify()
odoo_1                    |   File "/opt/odoo/custom/src/odoo/odoo/service/server.py", line 268, in __init__
odoo_1                    |     self.watcher = InotifyTrees(paths_to_watch, mask=INOTIFY_LISTEN_EVENTS, block_duration_s=.5)
odoo_1                    |   File "/usr/local/lib/python3.6/site-packages/inotify/adapters.py", line 372, in __init__
odoo_1                    |     self.__load_trees(paths)
odoo_1                    |   File "/usr/local/lib/python3.6/site-packages/inotify/adapters.py", line 395, in __load_trees
odoo_1                    |     self._i.add_watch(path, self._mask)
odoo_1                    |   File "/usr/local/lib/python3.6/site-packages/inotify/adapters.py", line 95, in add_watch
odoo_1                    |     wd = inotify.calls.inotify_add_watch(self.__inotify_fd, path_bytes, mask)
odoo_1                    |   File "/usr/local/lib/python3.6/site-packages/inotify/calls.py", line 35, in _check_nonnegative
odoo_1                    |     (result,))
odoo_1                    | inotify.calls.InotifyError: Call failed (should not be -1): (-1) ERRNO=(0)
```

The editors seems don't create temporary files (I checked with ``inotifywait -m . -r -e create  -e modify -e moved_to  -e delete -e delete_self``

**Comment by Yajo** [comment]
You have to follow these instructions: https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc

**Comment by yelizariev** [comment]
I made some further investigation: https://github.com/odoo/odoo/issues/60180

**Comment by pedrobaeza** [comment]
I was hit by this, so thank you very much for investigating this.
